# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance


appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: S

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Technical University of Munich'
    description: 'Shahriar Iqbal Zame â€“ Research Associate and PhD Candidate at TUM, Chair of Transportation Systems Engineering'
    twitter: ''
  analytics:
    # Use a GA4 Measurement ID such as G-XXXXXXXXXX when available.
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''


# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '@ {year} Shahriar Iqbal Zame. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false


# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us


# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
    extra_languages:
      - r
      - latex
  math:
    enable: true
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/shahriarzame/shahriarzame.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: false
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
